### PR TITLE
initial ICommandManager

### PR DESCRIPTION
**Pull request by aesalazar**
@0xd4d.  Sorry to take so long to get to this, been working on it in my "spare" time.  I think I finally have a basic enough understanding of dnSpy's architecture to take a stab at making the keys more dynamic.

This isnt a "real" PR, it is just a way to contact you with the changes.  This is in NO way meant to be final - quite the opposite.  But I wanted to get something in front of you to see if this is anything like the direction you were thinking.

I created a `ICommandManager` and export the class via MEF.  I wasn't sure the best place to put it.  For now, I made a static ref in `ICommandService` so other classes could get to it.  As an example, I used `TabElementZoomer` since it only had a few keys to convert but does not have an importing ctor.   

The manager is using a bunch of nested collection right now just to get something going.  Probably makes sense to create a real class for it.

As for saving the settings, I simply parse/unparse the collection to `ISettingsService`.  Again, not sure if there is a better way - can I have it somehow automatically serialize a class?

Again, this is very rough so any and all feedback is welcomed.

### CODE REVIEW

**Comment by 0xd4d** [comment]
I didn't see this because I only get notified when someone creates an issue or a PR in one of my repos.

ICommandManager depends on WPF (System.Windows.Input). It should be possible to do this without depending on a UI framework.

We need a command class that is exported. This code needs no WPF refs.

- It has a unique human readable name
- it has Execute() and CanExecute() methods
- I'm not sure yet if it should also specify the default key bindings or if that should be in some keybindings file
- It also needs to specify which UI control it depends on, but it should do that without depending on WPF. Existing code that uses IWpfCommandService already does this by using a Guid and that Guid can be used here too.

The code would perhaps look something like this:

```C#
[ExportCommand("My.Unique.Command.Name", SomeUIControlGuid, Key = "Ctrl+C")]
sealed class MyUniqueCommand : ISomeCommandInterface {
	public bool CanExecute(...) { ... }
	public void Execute(...) { ... }
}
```

Since we already have a IWpfCommandService interface that's used by the WPF code, it could then initialize all exported commands belonging to that UI control. It would find all exported commands with key bindings, and add them to the WPF control.

**Comment by aesalazar** [comment]
I think I get the gist of what you are saying. Definitely can do it without WPF references, this was just to gets something up and running quickly.

I like the idea of putting all default key bindings in a file.  Just need to validate it on startup if we are expecting the user to edit it so it can provide specific feedback if they get it wrong.

When you refer to `IWpfCommandService `, it sounds like you are saying that **it** would contain `ICommandManager`?  So, it would use the manager to load the keys into the specific UI Controls?

Now what about in the case of `TabElementZoomer`?  I picked it specifically because it was so far down the class breadcrumb trail.  e.g. `TabElementZoomer` <- `TabContentImpl ` <- `DocumentTabService`.  I assume we do not want to use a `static` instance.  But, since it is `DocumentTabService` that has the importing constructor, would it be THERE that we create the hook for `IWpfCommandService` and pass it down the dependency tree?

**Comment by 0xd4d** [comment]
> When you refer to IWpfCommandService , it sounds like you are saying that it would contain ICommandManager? So, it would use the manager to load the keys into the specific UI Controls?

It already does that, but it's the callers that tell it which keys and which commands to use, so it would need to be updated to do it automatically, i.e., the callers should only let it know about the UI object + the guid and it would find all commands with key bindings and add them.

> Now what about in the case of TabElementZoomer? I picked it specifically because it was so far down the class breadcrumb trail. e.g. TabElementZoomer <- TabContentImpl <- DocumentTabService. I assume we do not want to use a static instance. But, since it is DocumentTabService that has the importing constructor, would it be THERE that we create the hook for IWpfCommandService and pass it down the dependency tree?

Yes, it's a little ugly to have to pass all of these args to its ctor but it's better than using statics.

**Comment by aesalazar** [comment]
Ok, so some like this then:

	using System;
	using System.ComponentModel.Composition;

	namespace dnSpy.Contracts.DnSpy.Command {

		public interface IUserCommand {

		}

		public interface IUserCommandMeta {

			string CommandName { get; }
			Guid Guid { get; }
			string Key { get; }
			string Modifiers { get; }
		}

		[MetadataAttribute, AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
		public sealed class ExportUserCommandAttribute : ExportAttribute, IUserCommandMeta {

			public ExportUserCommandAttribute(string commandName, Guid guid, string key, string modifiers) {
				CommandName = commandName;
				Guid = guid;
				Key = key;
				Modifiers = modifiers;
			}

			public string CommandName { get; }
			public Guid Guid { get; }
			public string Key { get; }
			public string Modifiers { get; }
		}
	}

If so, a few more questions:

- Is there functionality that I can use to serialize/deserialize this already?
- Should we save in the main settings file or a different one?
- Since we do not want System.Windows.Input should we simply stick with strings for the types?  Or maybe Enums?

**Comment by 0xd4d** [comment]
Key and Modifiers can be in the same string, eg. "Ctrl+Alt+Del"

IUserCommandMeta -> IUserCommandMetadata so it's consistent with other metadata interfaces.

CommandName -> Name since Command is already part of the interface name.

Guid -> I assume this is the UI object's Guid, but it's not obvious from the name. Also the type is `Guid` but attributes can't use it so it must be a `string`

> 
> If so, a few more questions:
> 
>     * Is there functionality that I can use to serialize/deserialize this already?

There's no such code.

> 
>     * Should we save in the main settings file or a different one?

dnSpy.xml so there's just one file.

> 
>     * Since we do not want System.Windows.Input should we simply stick with strings for the types?  Or maybe Enums?

Strings is easier, and the parser will be trivial.

**Comment by aesalazar** [comment]
Sorry to take so long with this.  I work on it during my "free" time which is not much these days.

Take a look that the what I just pushed.  Right now `ICommandManager` is orphaned since I wanted to focus on the `ExportUserCommand` attribute.  I implemented it for the Tab Zoomer control and it seems to work.  If it was what you were thinking I can work on serialization next.  Once that is done, it should simply me a matter of finding all of the controls that need to switch over.

I starting using the `KeyShortcut` and `KeyInput` classes but quickly realized they would need a decent amount of refactoring to get user friendly output.  I was worried it may break other things along the way.  So, for now, I just did my own parsing.

Do you envision eventually eliminating the need for the `IWpfCommand` class? I called mine `IWpfUserCommand` for now to keep them separate but can always change it later.

**Comment by 0xd4d** [comment]
You should rebase on top of master so it's easier to see only your changes.

It's still too much work to create a command. You should just be able to do this:

1. Export a command with or without a default keyboard shortcut
2. Let some service know about the UI <-> GUID (can only be done at runtime)

That's it, it should now work. If it's a menu command, its keyboard shortcut will be shown next time the menu is shown.

Right now you also have to add the commands to the UI. And if it's a menu command, you have to add the keyboard shortcut too.


The default keyboard shortcuts that get exported should look the way most people write them, eg. "Ctrl+Alt+Del" instead of "Ctrl Alt Del". The parser will still be trivial with this change.


Some code style issues that I didn't mention before:

- No empty line after namespaces, class, interface, struct '{' and before '}'
- Don't add any #regions
- when splitting up code on new lines, the '.', '&&', etc is at the end of the previous line not beginning of the new line
- 'internal' (types) and 'private' (members) modifiers aren't needed

**Pull request closed without merging**
